### ISSUE TITLE
Links to StackOverflow profiles display the numeric ID instead of the StackOverflow username

### ISSUE THREAD

**Issue by DylanSp** [TampaDevs/talent.tampa.dev#33]
## Describe the bug

When a developer's page contains a link to their StackOverflow account, the numeric ID for the SO account is shown, instead of the username. For instance, linking to my profile at https://stackoverflow.com/users/5847190/dylansp displays the ID "5847190" instead of "dylansp" or "DylanSp".

## To reproduce

* Edit your developer profile to contain a link to your StackOverflow account.
* View your developer profile page and look at the sidebar.

## Expected behavior

The link's text is the StackOverflow username.

## Actual behavior

The link's text is the numeric ID for the StackOverflow profile.

## Screenshots

![link to stack overflow with numeric ID](https://github.com/TampaDevs/talent.tampa.dev/assets/4009007/315c8c48-48c2-48d9-8915-099df6eb0076)

## Additional context

When adding a link to a StackOverflow account from the Edit Profile page, it looks like the ID is truncated at the first `/`. I entered `5847190/dylansp` in the field and saved it; when editing my profile again, that field only showed `5847190`.

**Comment by iBotPeaches** [comment]
I was curious why this was, but it seemed very much intentional when you look at test suite: https://github.com/TampaDevs/talent.tampa.dev/blob/master/test/models/concerns/developers/has_online_profiles_test.rb#L89-L104

So I tracked it back to PR it was added in: https://github.com/joemasilotti/railsdevs.com/pull/581

Which appears to be incorrect in 2024's state of StackOverflow.

They call out

> Stack Overflow user profile URL is of the format /users/<id>/<username>
> /users/<id>/<username> will be redirected to /users/<id>

The inverse is actually true now. SO will redirect from `/users/<id>` to `/users/<id>/<username>`

```
➜  ~ curl -I https://stackoverflow.com/users/455008
HTTP/2 301 
location: /users/455008/connor-tumbleson
```

**Comment by chtzvt** [comment]
@iBotPeaches Thanks for the investigation-- I'll close this, given that it seems to be expected behavior 🙏
